version: '3'

services:
  dns:
    image: andyshinn/dnsmasq:2.83
    container_name: dns-server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/config:/etc/dnsmasq.d
    networks:
      - network1

  samba:
    image: dperson/samba:latest
    container_name: samba-server
    ports:
      - "139:139"
      - "5445:445"
    volumes:
      - ./samba/config:/etc/samba/
      - ./samba/data:/data
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - network1

  ftp:
    image: fauria/vsftpd:latest
    container_name: ftp-server
    environment:
      - FTP_USER=usuario
      - FTP_PASS=senha
    ports:
      - "21:21"
      - "20:20"
    volumes:
      - ./ftp/data:/home/vsftpd
    networks:
      - network1

  ldap:
    image: osixia/openldap:latest
    container_name: ldap-server
    environment:
      - LDAP_ORGANISATION="Empresa"
      - LDAP_DOMAIN="empresa.com"
      - LDAP_ADMIN_PASSWORD="admin123"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
    networks:
      - network1

  web:
    image: ubuntu/apache2:2.4-20.04_beta
    container_name: apache-server
    volumes:
      - ./web/content:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network1

  iptables:
    image: ubuntu:latest
    container_name: iptables-server
    command: bash -c "apt-get update && apt-get install -y iptables && iptables -F && iptables -P INPUT DROP && iptables -P FORWARD DROP && iptables -P OUTPUT ACCEPT && iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT && tail -f /dev/null"
    privileged: true
    networks:
      - network1

  dhcp:
    image: portnox/portnox-dhcp:latest
    container_name: dhcp-server
    command: bash -c "dhcpd -f -d -cf /etc/dhcp/dhcpd.conf && tail -f /dev/null"
    volumes:
      - ./dhcp/config:/etc/dhcp
    network_mode: "host"

networks:
  network1:
    driver: bridge